### ISSUE TITLE
Show topictitlecolor only in first post

### ISSUE THREAD

**Issue by jan-2017** [DavidIQ/topictitlecolor#11]
Hello.If i install topictitlecolor i can change the color in every reply.Does it only make sense to allow the function for the first post? Bye Jan

**Comment by DavidIQ** [comment]
It doesn’t show outside of the first post. Make sure that you have the latest files.
https://github.com/DavidIQ/topictitlecolor/blob/master/event/main_listener.php#L103

**Comment by jan-2017** [comment]
Hello.That is right. Color does not appear in second , third , ... post - but the color panel appears in every new post in topic. Would not it be better to show the color panel only in the first post? Bye Jan
