### ISSUE TITLE
Include favorites

### ISSUE THREAD

**Issue by jan-2017** [DavidIQ/topictitlecolor#12]
Hello.Does it make sense to insert a line above the color palette in which five favorite colors are visible? That´s my idea ;) Bye Jan

**Comment by DavidIQ** [comment]
Favorite colors? So the admin would have to define those?

**Comment by jan-2017** [comment]
Yes. Admin or normal users. Or "the last used colors" for example. Bye Jan

**Comment by DavidIQ** [comment]
I don't understand the use case for this.

**Comment by jan-2017** [comment]
No problem. It was only an idea.Bye Jan
